repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-merge-conflict
        -   id: debug-statements
  -   repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
        - id: black
  -   repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        -   id: isort
